import React from "react";
import { View, Text, StyleSheet } from "react-native";
import { ListRow } from "./ListRow";
import { DetailSheet, DetailRow } from "./DetailSheet";
import { EmptyState } from "./Layout";
import { SecondaryButton } from "./Buttons";
import { DownloadButton } from "./DownloadButton";
import { NEUTRAL } from "@/theme/themes";
import { useAppTheme } from "@/context/ThemeContext";
import { getDocumentDetail, getLabReportFile } from "@/api/portal";
import { downloadDataUri, downloadHtmlAsPdf } from "@/utils/fileHelpers";
import { LabOrder } from "@/api/types";
import { FlaskConical } from "lucide-react-native";

const LAB_STATUS_TONE: Record<string, "success" | "warning" | "danger" | "neutral"> = {
  completed: "success",
  processing: "warning",
  collected: "warning",
  ordered: "neutral",
  cancelled: "danger",
};

const LAB_STATUS_COLOR: Record<string, string> = {
  completed: NEUTRAL.success,
  processing: NEUTRAL.warning,
  collected: NEUTRAL.warning,
  cancelled: NEUTRAL.danger,
};

function labStatusLabel(status: string): string {
  return status.charAt(0).toUpperCase() + status.slice(1);
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function buildReportHtml(order: LabOrder): string {
  const rows = (order.report?.items || [])
    .map(
      (it) => `
        <tr${it.is_abnormal ? ' style="color:#B23A3A;font-weight:700;"' : ""}>
          <td>${escapeHtml(it.parameter_name)}</td>
          <td>${escapeHtml(it.result_value)} ${escapeHtml(it.unit)}</td>
          <td>${escapeHtml(it.reference_range || "—")}</td>
        </tr>`
    )
    .join("");
  return `
    <html>
      <head><meta charset="utf-8" /></head>
      <body style="font-family:Helvetica,Arial,sans-serif;color:#0C2340;padding:24px;">
        <h2 style="margin-bottom:2px;">${escapeHtml(order.test_name)}</h2>
        <p style="color:#5A6B7A;margin-top:0;">${escapeHtml(order.hospital)}</p>
        <p style="font-size:12px;color:#5A6B7A;">
          Ordered: ${escapeHtml(order.ordered_at.slice(0, 10))}
          ${order.report?.delivered_at ? ` &middot; Delivered: ${escapeHtml(order.report.delivered_at.slice(0, 10))}` : ""}
        </p>
        ${order.report?.result_summary ? `<p>${escapeHtml(order.report.result_summary)}</p>` : ""}
        ${
          rows
            ? `<table style="width:100%;border-collapse:collapse;margin-top:12px;font-size:13px;">
                <thead>
                  <tr style="text-align:left;border-bottom:1px solid #C9D6E3;">
                    <th style="padding:6px 8px;">Parameter</th>
                    <th style="padding:6px 8px;">Result</th>
                    <th style="padding:6px 8px;">Reference range</th>
                  </tr>
                </thead>
                <tbody>${rows}</tbody>
              </table>`
            : ""
        }
        <p style="font-size:11px;color:#8B98A5;margin-top:24px;">
          Generated by the Atomwalk patient app. For questions, contact support@atomwalk.com.
        </p>
      </body>
    </html>`;
}

/**
 * `expandedId`/`onToggleExpand` are reused here as "which order's detail
 * sheet is open" (a tap opens it, the backdrop/close button clears it) —
 * same controlled-from-parent contract HealthScreen already had, just
 * repurposed now that everything lives in a bottom sheet instead of an
 * always-expanded inline card.
 */
export function LabOrdersList({
  orders,
  expandedId,
  onToggleExpand,
  onChoose,
  savingId,
}: {
  orders: LabOrder[];
  expandedId: number | null;
  onToggleExpand: (id: number) => void;
  onChoose: (order: LabOrder, choice: "in_house" | "outside") => void;
  savingId: number | null;
}) {
  const { theme } = useAppTheme();

  if (orders.length === 0) {
    return <EmptyState text="No lab tests ordered yet." />;
  }

  const open = orders.find((o) => o.id === expandedId) || null;

  const downloadOrder = async (order: LabOrder) => {
    // Prefer the real file the lab uploaded (PortalLabReportFileView) when
    // there is one — only fall back to the report rebuilt from structured
    // result items when no file was attached.
    if (order.report?.status === "delivered" && order.report.has_file) {
      const file = await getLabReportFile(order.tenant_db, order.id);
      await downloadDataUri(file.file_name || `${order.test_name.replace(/[^\w -]/g, "")}.pdf`, file.file_data);
    } else if (order.report?.status === "delivered") {
      await downloadHtmlAsPdf(`${order.test_name.replace(/[^\w -]/g, "")}.pdf`, buildReportHtml(order));
    } else if (order.attached_document) {
      const full = await getDocumentDetail(order.attached_document.id);
      await downloadDataUri(full.file_name || full.title, full.file_data);
    }
  };

  return (
    <>
      {orders.map((order) => (
        <ListRow
          key={order.id}
          icon={FlaskConical}
          title={order.test_name}
          subtitle={`${order.hospital}${order.price ? ` · ₹${order.price}` : ""}`}
          pillLabel={labStatusLabel(order.status)}
          pillTone={LAB_STATUS_TONE[order.status] || "neutral"}
          onPress={() => onToggleExpand(order.id)}
        />
      ))}

      <DetailSheet visible={!!open} onClose={() => open && onToggleExpand(open.id)} title={open?.test_name || ""}>
        {open && (
          <>
            <DetailRow label="Hospital" value={open.hospital} />
            <DetailRow label="Ordered" value={open.ordered_at.slice(0, 10)} />
            {!!open.price && <DetailRow label="Price" value={`₹${open.price}`} />}
            <DetailRow label="Status" value={labStatusLabel(open.status)} valueColor={LAB_STATUS_COLOR[open.status]} />

            {open.patient_choice === "pending" ? (
              <View style={styles.choiceBox}>
                <Text style={styles.choiceLabel}>Where would you like this test done?</Text>
                <View style={styles.choiceRow}>
                  <SecondaryButton
                    label="At this hospital"
                    loading={savingId === open.id}
                    onPress={() => onChoose(open, "in_house")}
                    style={{ flex: 1, paddingVertical: 9 }}
                  />
                  <SecondaryButton
                    label="Elsewhere"
                    loading={savingId === open.id}
                    onPress={() => onChoose(open, "outside")}
                    style={{ flex: 1, paddingVertical: 9 }}
                  />
                </View>
              </View>
            ) : (
              <DetailRow
                label="Testing"
                value={
                  (open.patient_choice === "in_house" ? "In-house" : "Outside") +
                  (open.payment_status !== "unpaid" ? ` · ${open.payment_status === "paid" ? "Paid" : "Payment pending"}` : "")
                }
              />
            )}

            {open.report?.status === "delivered" ? (
              <View style={styles.reportBox}>
                <Text style={styles.reportTitle}>Report</Text>
                {!!open.report.result_summary && <Text style={styles.summary}>{open.report.result_summary}</Text>}
                {(open.report.items || []).map((it, i) => (
                  <View key={i} style={styles.paramRow}>
                    <Text style={styles.labParam}>{it.parameter_name}</Text>
                    <Text style={[styles.labValue, it.is_abnormal && { color: NEUTRAL.danger, fontWeight: "700" }]}>
                      {it.result_value} {it.unit}
                      {it.reference_range ? `  (ref: ${it.reference_range})` : ""}
                    </Text>
                  </View>
                ))}
              </View>
            ) : open.attached_document ? (
              <Text style={styles.notice}>Report attached: {open.attached_document.title}</Text>
            ) : (
              <Text style={styles.notice}>Report not available yet.</Text>
            )}

            {(open.report?.status === "delivered" || !!open.attached_document) && (
              <DownloadButton fileLabel={open.test_name} onDownload={() => downloadOrder(open)} style={{ marginTop: 14, paddingVertical: 9 }} />
            )}
          </>
        )}
      </DetailSheet>
    </>
  );
}

const styles = StyleSheet.create({
  choiceBox: { marginTop: 6 },
  choiceLabel: { fontSize: 12, color: NEUTRAL.textSecondary },
  choiceRow: { flexDirection: "row", gap: 8, marginTop: 8 },
  reportBox: { marginTop: 6 },
  reportTitle: { fontSize: 12.5, fontWeight: "600", color: NEUTRAL.textPrimary, marginBottom: 6 },
  summary: { fontSize: 11.5, color: NEUTRAL.textSecondary, marginBottom: 6 },
  paramRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 6, borderBottomWidth: 0.5, borderBottomColor: NEUTRAL.surfaceAlt },
  labParam: { fontSize: 11.5, color: NEUTRAL.textPrimary, flexShrink: 1 },
  labValue: { fontSize: 11.5, color: NEUTRAL.textSecondary },
  notice: { fontSize: 11.5, color: NEUTRAL.textMuted, marginTop: 6 },
});
